version: "3.7"
services:
  db:
    image: postgres
    container_name: database
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - backend/.env-non-dev
    networks:
      - my-network

  fake-db:
    image: postgres
    container_name: fake-database
    command: -p 5431
    expose:
      - 5431
    ports:
      - "5431:5431"
    env_file:
      - backend/.env-fake-non-dev
    networks:
      - my-network

  backend:
    build:
      context: backend
    env_file:
      - backend/.env-non-dev
    container_name: backend
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./backend/data/verification:/code/backend/data/verification
    depends_on:
      - db
      - fake-db
    command: [ "/code/backend/docker/app.sh" ]
    restart: on-failure
    networks:
      - my-network

  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - my-network

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
