version: "3.7"
services:
  db:
    image: postgres
    container_name: database
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev

  fake-db:
    image: postgres
    container_name: fake-database
    command:
      -p 5431
    expose:
      - 5431
    ports:
      - "5431:5431"
    env_file:
      - .env-fake-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: application
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
      - fake-db
    command: [ "/code/docker/app.sh" ]