"""add: loan id

Revision ID: 046f4a11c34a
Revises: ccf8595085f7
Create Date: 2023-03-15 01:50:51.516268

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '046f4a11c34a'
down_revision = 'ccf8595085f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('period', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('user', sa.Column('loan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'loan', ['loan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'loan_id')
    op.drop_table('loan')
    # ### end Alembic commands ###
