"""fix: user-passport

Revision ID: 05134bae0514
Revises: 773e80faac5f
Create Date: 2023-03-16 02:07:08.842016

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05134bae0514'
down_revision = '773e80faac5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_passport_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'passport_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_passport_id_fkey', 'user', 'passport', ['passport_id'], ['id'])
    # ### end Alembic commands ###
