"""Balance DB

Revision ID: 16df997abee8
Revises: db08ab24fa9f
Create Date: 2023-03-21 20:31:02.648482

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16df997abee8'
down_revision = 'db08ab24fa9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('loan_id', sa.Integer(), nullable=True),
                    sa.Column('creation_date', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    balance_table = sa.Table('balance', sa.MetaData(), autoload_with=op.get_bind())

    op.bulk_insert(balance_table, [
        {'id': 0, 'amount': 1000000, 'user_id': None, 'loan_id': None, 'creation_date': datetime.utcnow()},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance')
    # ### end Alembic commands ###
