"""add:unique user id

Revision ID: 35fb03d899b1
Revises: e71875cea86a
Create Date: 2023-03-17 18:41:16.962912

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '35fb03d899b1'
down_revision = 'e71875cea86a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'passport', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passport', type_='unique')
    # ### end Alembic commands ###
