"""fix: user-passport

Revision ID: 4d7b0a986da7
Revises: eb2ea740417f
Create Date: 2023-03-16 02:00:24.907182

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4d7b0a986da7'
down_revision = 'eb2ea740417f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
