"""fix: user-passport:one-to-one

Revision ID: 5313ca08de51
Revises: 16a267a97ee4
Create Date: 2023-03-16 02:53:11.272351

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5313ca08de51'
down_revision = '16a267a97ee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
