"""fix:user-passport:relationship

Revision ID: 5bc8df6bf811
Revises: b0117bcb5840
Create Date: 2023-03-17 00:09:30.572843

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5bc8df6bf811'
down_revision = 'b0117bcb5840'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passport', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_passport_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'passport_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_passport_id_fkey', 'user', 'passport', ['passport_id'], ['id'])
    op.drop_constraint(None, 'passport', type_='foreignkey')
    op.drop_column('passport', 'user_id')
    # ### end Alembic commands ###
