"""fix: user-passport

Revision ID: 695b440486ce
Revises: 05134bae0514
Create Date: 2023-03-16 02:22:02.571421

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '695b440486ce'
down_revision = '05134bae0514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'passport', ['passport_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'passport_id')
    # ### end Alembic commands ###
