"""fix: user-passport

Revision ID: 773e80faac5f
Revises: 4d7b0a986da7
Create Date: 2023-03-16 02:01:38.646449

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '773e80faac5f'
down_revision = '4d7b0a986da7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
