"""del: username

Revision ID: 82fb886a9002
Revises: 046f4a11c34a
Create Date: 2023-03-15 16:30:33.526500

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '82fb886a9002'
down_revision = '046f4a11c34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
