"""upd: relationships

Revision ID: 8f08edbafcbe
Revises: 989191763f8b
Create Date: 2023-03-15 17:43:31.657364

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8f08edbafcbe'
down_revision = '989191763f8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
