"""fix: user-passport:lazy=False

Revision ID: 925e8198e27f
Revises: d7873fe58fa7
Create Date: 2023-03-16 02:42:02.074708

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '925e8198e27f'
down_revision = 'd7873fe58fa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
