"""upd: relationships

Revision ID: 989191763f8b
Revises: b7a20149a778
Create Date: 2023-03-15 17:39:00.075403

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '989191763f8b'
down_revision = 'b7a20149a778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loan', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('loan_user_id_fkey', 'loan', type_='foreignkey')
    op.create_foreign_key(None, 'loan', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.create_foreign_key('loan_user_id_fkey', 'loan', 'user', ['user_id'], ['id'])
    op.alter_column('loan', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
