"""fix:user-passport:relationship

Revision ID: b0117bcb5840
Revises: 5313ca08de51
Create Date: 2023-03-16 23:46:38.872627

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b0117bcb5840'
down_revision = '5313ca08de51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('passport_user_id_fkey', 'passport', type_='foreignkey')
    op.drop_column('passport', 'user_id')
    op.add_column('user', sa.Column('passport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'passport', ['passport_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'passport_id')
    op.add_column('passport', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('passport_user_id_fkey', 'passport', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
