"""upd: relationships

Revision ID: b7a20149a778
Revises: 82fb886a9002
Create Date: 2023-03-15 17:33:34.747345

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b7a20149a778'
down_revision = '82fb886a9002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_loan_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'loan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_loan_id_fkey', 'user', 'loan', ['loan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_column('loan', 'user_id')
    # ### end Alembic commands ###
