"""edit: role permissions

Revision ID: ccf8595085f7
Revises: 37e33fdecd52
Create Date: 2023-03-15 00:45:53.318864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf8595085f7'
down_revision = '37e33fdecd52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'permissions',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'permissions',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    # ### end Alembic commands ###
