"""fix: user-passport:lazy=False

Revision ID: cec79af745e4
Revises: 925e8198e27f
Create Date: 2023-03-16 02:42:54.456684

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cec79af745e4'
down_revision = '925e8198e27f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
