"""fix: user-passport

Revision ID: d7873fe58fa7
Revises: 695b440486ce
Create Date: 2023-03-16 02:37:56.719926

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd7873fe58fa7'
down_revision = '695b440486ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('passport_user_id_fkey', 'passport', type_='foreignkey')
    op.drop_column('passport', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('passport_user_id_fkey', 'passport', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
