"""del:data passport column

Revision ID: e71875cea86a
Revises: 5bc8df6bf811
Create Date: 2023-03-17 17:49:05.991918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e71875cea86a'
down_revision = '5bc8df6bf811'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passport', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passport', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
