"""add: user-passport

Revision ID: eb2ea740417f
Revises: d065204ce6a8
Create Date: 2023-03-15 20:27:05.220852

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eb2ea740417f'
down_revision = 'd065204ce6a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.String(length=120), nullable=False),
                    sa.Column('filename', sa.String(), nullable=True),
                    sa.Column('content_type', sa.String(), nullable=True),
                    sa.Column('data', sa.LargeBinary(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('number')
                    )
    op.add_column('user', sa.Column('passport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'passport', ['passport_id'], ['id'])
    op.drop_column('user', 'hashed_passport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_passport', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'passport_id')
    op.drop_table('passport')
    # ### end Alembic commands ###
