"""is_active

Revision ID: f298ce90ed2c
Revises: 7fa0528d3495
Create Date: 2023-03-18 03:46:58.666277

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f298ce90ed2c'
down_revision = '7fa0528d3495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
